import pymysql

conexao = pymysql.connect ( host='localhost',
                            user='root', passwd='',database='db_prensa_software')
cursor = conexao.cursor()

cursor.execute(f"SELECT altura_inicial FROM id_cp_cbr;") 
altura_inicial = str(cursor.fetchall()); altura_inicial = altura_inicial.replace("((", ""); altura_inicial = altura_inicial.replace(",),)", "")
cursor.execute(f"SELECT exp_umidade_otima  FROM id_cp_cbr;") 
exp_umidade_otima = str(cursor.fetchall()); exp_umidade_otima = exp_umidade_otima.replace("((", ""); exp_umidade_otima = exp_umidade_otima.replace(",),)", "")
cursor.execute(f"SELECT id_molde FROM id_cp_cbr;") 
id_molde = str(cursor.fetchall()); id_molde = id_molde.replace("(('", ""); id_molde = id_molde.replace("',),)", "")
cursor.execute(f"SELECT leitura_exp0 FROM id_cp_cbr;") 
leitura_exp0 = str(cursor.fetchall()); leitura_exp0 = leitura_exp0.replace("((", ""); leitura_exp0 = leitura_exp0.replace(",),)", "")
cursor.execute(f"SELECT leitura_exp1 FROM id_cp_cbr;") 
leitura_exp1 = str(cursor.fetchall()); leitura_exp1 = leitura_exp1.replace("((", ""); leitura_exp1 = leitura_exp1.replace(",),)", "")
cursor.execute(f"SELECT leitura_exp2 FROM id_cp_cbr;") 
leitura_exp2 = str(cursor.fetchall()); leitura_exp2 = leitura_exp2.replace("((", ""); leitura_exp2 = leitura_exp2.replace(",),)", "")
cursor.execute(f"SELECT leitura_exp3 FROM id_cp_cbr;") 
leitura_exp3 = str(cursor.fetchall()); leitura_exp3 = leitura_exp3.replace("((", ""); leitura_exp3 = leitura_exp3.replace(",),)", "")
cursor.execute(f"SELECT leitura_exp4 FROM id_cp_cbr;") 
leitura_exp4 = str(cursor.fetchall()); leitura_exp4 = leitura_exp4.replace("((", ""); leitura_exp4 = leitura_exp4.replace(",),)", "")
cursor.execute(f"SELECT massa_amosta FROM id_cp_cbr;") 
massa_amosta = str(cursor.fetchall()); massa_amosta = massa_amosta.replace("((", ""); massa_amosta = massa_amosta.replace(",),)", "")
cursor.execute(f"SELECT massa_amostra_cilindro FROM id_cp_cbr;") 
massa_amostra_cilindro = str(cursor.fetchall()); massa_amostra_cilindro = massa_amostra_cilindro.replace("((", ""); 
massa_amostra_cilindro = massa_amostra_cilindro.replace(",),)", "")
cursor.execute(f"SELECT massa_cilindro FROM id_cp_cbr;") 
massa_cilindro = str(cursor.fetchall()); massa_cilindro = massa_cilindro.replace("((", ""); massa_cilindro = massa_cilindro.replace(",),)", "")
cursor.execute(f"SELECT massa_esp_ap_seca FROM id_cp_cbr;") 
massa_esp_ap_seca = str(cursor.fetchall()); massa_esp_ap_seca = massa_esp_ap_seca.replace("((", ""); massa_esp_ap_seca = massa_esp_ap_seca.replace(",),)", "")
cursor.execute(f"SELECT peso_esp_umido FROM id_cp_cbr;") 
peso_esp_umido = str(cursor.fetchall()); peso_esp_umido = peso_esp_umido.replace("((", ""); peso_esp_umido = peso_esp_umido.replace(",),)", "")
cursor.execute(f"SELECT teor_umidade_media FROM id_cp_cbr;") 
teor_umidade_media=str(cursor.fetchall());teor_umidade_media=teor_umidade_media.replace("((", "");teor_umidade_media = teor_umidade_media.replace(",),)", "")
cursor.execute(f"SELECT volume FROM id_cp_cbr;") 
volume = str(cursor.fetchall()); volume = volume.replace("((", ""); volume = volume.replace(",),)", "")
cursor.execute(f"SELECT amostra FROM id_ensaio_cbr;") 
amostra = str(cursor.fetchall()); amostra = amostra.replace("(('", ""); amostra = amostra.replace("',),)", "")
cursor.execute(f"SELECT dia FROM id_ensaio_cbr;") 
dia = str(cursor.fetchall()); dia = dia.replace("(('", ""); dia = dia.replace("',),)", "")
cursor.execute(f"SELECT energia FROM id_ensaio_cbr;") 
energia = str(cursor.fetchall()); energia = energia.replace("((", ""); energia = energia.replace(",),)", "")
cursor.execute(f"SELECT furo FROM id_ensaio_cbr;")
furo = str(cursor.fetchall()); furo = furo.replace("(('", ""); furo = furo.replace("',),)", "")
cursor.execute(f"SELECT material FROM id_ensaio_cbr;")
material = str(cursor.fetchall()); material = material.replace("(('", ""); material = material.replace("',),)", "")
cursor.execute(f"SELECT obra FROM id_ensaio_cbr;")
obra= str(cursor.fetchall()); obra = obra.replace("(('", ""); obra = obra.replace("',),)", "")
cursor.execute(f"SELECT operador FROM id_ensaio_cbr;")
operador = str(cursor.fetchall()); operador = operador.replace("(('", ""); operador = operador.replace("',),)", "")
cursor.execute(f"SELECT subtrecho FROM id_ensaio_cbr;")
subtrecho = str(cursor.fetchall()); subtrecho = subtrecho.replace("(('", ""); subtrecho = subtrecho.replace("',),)", "")
cursor.execute(f"SELECT trecho FROM id_ensaio_cbr;")
trecho = str(cursor.fetchall()); trecho = trecho.replace("(('", ""); trecho = trecho.replace("',),)", "")
cursor.close()


print(trecho)     

