import pymysql

conexao = pymysql.connect ( host='localhost',
                            user='root', passwd='',database='db_prensa_software')
cursor = conexao.cursor()
cursor.execute(f"SELECT registro FROM ensaio_marshall;") 
registro = str(cursor.fetchall()); registro = registro.replace("((", ""); registro = registro.replace(",),)", "")
cursor.execute(f"SELECT dia FROM ensaio_marshall;") 
dia = str(cursor.fetchall()); dia = dia.replace("((", ""); dia = dia.replace(",),)", "")
cursor.execute(f"SELECT id_cp FROM ensaio_marshall;") 
id_cp= str(cursor.fetchall()); id_cp = id_cp.replace("((", ""); id_cp = id_cp.replace(",),)", "")
cursor.execute(f"SELECT material FROM ensaio_marshall;") 
material = str(cursor.fetchall()); material = material.replace("((", ""); material = material.replace(",),)", "")
cursor.execute(f"SELECT obra FROM ensaio_marshall;") 
obra = str(cursor.fetchall()); obra = obra.replace("((", ""); obra = obra.replace(",),)", "")
cursor.execute(f"SELECT operador FROM ensaio_marshall;") 
operador = str(cursor.fetchall()); operador = operador.replace("((", ""); operador = operador.replace(",),)", "")
cursor.execute(f"SELECT trecho FROM ensaio_marshall;") 
trecho = str(cursor.fetchall()); trecho = trecho.replace("((", ""); trecho = trecho.replace(",),)", "")
cursor.execute(f"SELECT subtrecho FROM ensaio_marshall;") 
subtrecho = str(cursor.fetchall()); subtrecho = subtrecho.replace("((", ""); subtrecho = subtrecho.replace(",),)", "")
cursor.execute(f"SELECT peso_ar FROM ensaio_marshall;") 
peso_ar = str(cursor.fetchall()); peso_ar = peso_ar.replace("((", ""); peso_ar = peso_ar.replace(",),)", "")
cursor.execute(f"SELECT peso_imerso FROM ensaio_marshall;") 
peso_imerso = str(cursor.fetchall()); peso_imerso = peso_imerso.replace("((", ""); peso_imerso = peso_imerso.replace(",),)", "")
cursor.execute(f"SELECT volume FROM ensaio_marshall;") 
volume = str(cursor.fetchall()); volume = volume.replace("((", ""); volume = volume.replace(",),)", "")
cursor.execute(f"SELECT densi_aparente FROM ensaio_marshall;") 
densi_aparente = str(cursor.fetchall()); densi_aparente = densi_aparente.replace("((", ""); densi_aparente = densi_aparente.replace(",),)", "")
cursor.execute(f"SELECT densi_teorica FROM ensaio_marshall;") 
densi_teorica = str(cursor.fetchall()); densi_teorica = densi_teorica.replace("((", ""); densi_teorica = densi_teorica.replace(",),)", "")
cursor.execute(f"SELECT temperatura FROM ensaio_marshall;") 
temperatura = str(cursor.fetchall()); temperatura = temperatura.replace("((", ""); temperatura = temperatura.replace(",),)", "")
cursor.execute(f"SELECT vazios FROM ensaio_marshall;") 
vazios = str(cursor.fetchall()); vazios = vazios.replace("((", ""); vazios = vazios.replace(",),)", "")
cursor.execute(f"SELECT v_c_b FROM ensaio_marshall;") 
v_c_b = str(cursor.fetchall()); v_c_b = v_c_b.replace("((", ""); v_c_b = v_c_b.replace(",),)", "")
cursor.execute(f"SELECT v_a_m FROM ensaio_marshall;") 
v_a_m = str(cursor.fetchall()); v_a_m = v_a_m.replace("((", ""); v_a_m = v_a_m.replace(",),)", "")
cursor.execute(f"SELECT r_v_b FROM ensaio_marshall;") 
r_v_b = str(cursor.fetchall()); r_v_b = r_v_b.replace("((", ""); r_v_b = r_v_b.replace(",),)", "")
cursor.execute(f"SELECT amostra_antes FROM ensaio_marshall;") 
amostra_antes = str(cursor.fetchall()); amostra_antes = amostra_antes.replace("((", ""); amostra_antes = amostra_antes.replace(",),)", "")
cursor.execute(f"SELECT amostra_depois FROM ensaio_marshall;") 
amostra_depois = str(cursor.fetchall()); amostra_depois = amostra_depois.replace("((", ""); amostra_depois = amostra_depois.replace(",),)", "")
cursor.execute(f"SELECT peso_betume FROM ensaio_marshall;") 
peso_betume = str(cursor.fetchall()); peso_betume = peso_betume.replace("((", ""); peso_betume = peso_betume.replace(",),)", "")
cursor.execute(f"SELECT teor_betume FROM ensaio_marshall;") 
teor_betume = str(cursor.fetchall()); teor_betume = teor_betume.replace("((", ""); teor_betume = teor_betume.replace(",),)", "")
cursor.execute(f"SELECT comp_diame FROM ensaio_marshall;") 
comp_diame = str(cursor.fetchall()); comp_diame = comp_diame.replace("((", ""); comp_diame = comp_diame.replace(",),)", "")
cursor.execute(f"SELECT leit_deflet FROM ensaio_marshall;") 
leit_deflet = str(cursor.fetchall()); leit_deflet = leit_deflet.replace("((", ""); leit_deflet = leit_deflet.replace(",),)", "")

print(peso_ar, peso_imerso, volume, densi_aparente, densi_teorica, temperatura, vazios, v_c_b, v_a_m, r_v_b, amostra_antes, amostra_depois, peso_betume, teor_betume, comp_diame, leit_deflet)
